### ISSUE TITLE
CLI? 

### ISSUE THREAD

**Issue by dgdosen** [ohtake/slack2md#1]
I'm not sure how one would use this.

Is there a CLI to use this functionality with exported content?  In looking at the readme, I'm not sure how or why using git would be applicable...

Thanks!

**Comment by ohtake** [comment]
Hello, @dgdosen.

I just updated the doc with 1ba316bb6e8567a034e435d0caad288b59c8c6ed.
Does it help you?

**Comment by dgdosen** [comment]
you bet... closing
