### ISSUE TITLE
Failed to create output folder

### ISSUE THREAD

**Issue by cashmash** [ohtake/slack2md#2]
Hi,

nice sw.

Failing to create the output folder:

on
```
macOS Sierra Version 10.12.3
Go v1.8 https://golang.org/dl/
```

1. downloaded slack export
2. placed it under `slack_export` folder inside the `slack2md` directory
3. in Terminal run `go build`
4. run `slack2md`
4. Terminal output: 
`slack2md/slack2md ; exit;`
`slack2md/slack2md ; exit;`
`[Process completed]`
5. no folder `output`

**Comment by ohtake** [comment]
Thank you for reporting an issue.

Could you change app.go line 57 `_ = os.Mkdir(outputDir, os.ModeDir)` to the following?

```go
err := os.Mkdir(outputDir, os.ModeDir)
if err != nil {
  fmt.Println(err)
  return
}
```

**Comment by cashmash** [comment]
Thank you. 

Getting

```
mkdir output: file exists
```

But I am not seeing an `output` folder.

**Comment by ohtake** [comment]
I guess current working directory may be different from the path of `slack2md` directory.
How did you run `slack2md` in step 4? Running `./slack2md` in Terminal will execute `slack2md` binary in `slack2md` directory.

You can also print current working directory by adding two lines at the begining of `main` function of app.go.

```go
wd, _ := os.Getwd()
fmt.Println(wd)
```

**Comment by ohtake** [comment]
The issue is reproduced on an Ubuntu Xenial Docker container and Go 1.6.2.
Commit b8477303e94365d8e87469b35160c343de5ab0fb should fix it.
Please reopen the issue if any issue happens.
